---

- hosts: servers
  user: stark
  become: yes
  connection: ssh
  gather_facts: false
  
  tasks:
  
  - name: INSTALLING MYSQL PACKAGES AND DEPENDENCIES 
    apt:
      name:
      - 'mysql-client'
      - 'mysql-client-core-5.7' 
      - 'mysql-server-5.7'
      - 'mysql-testsuite-5.7'
      - 'mysqltcl'
      - 'mysql-client-5.7'
      - 'mysql-common'
      - 'mysql-server'
      - 'mysql-server-core-5.7'
      - 'mysql-testsuite'
      - 'mysql-utilities'
      - 'mysqltuner'
      state: absent
  
  - name: ENSURE THAT THE SERVICE IS RUNNING AFTER INSTALLATION
    service:
      name: mysql 
      state: started
  
  - name: ENABLE MYSQL SERVICE TO BE LOADED AT BOOT
    command: systemctl disable mysql

...
