---

- hosts: jadi
  gather_facts: false
  connection: ssh

  tasks:

  - name: CHANGING KERNEL SWAPPINESS TO 1
    sysctl:
       name: vm.swappiness
       value: 1

  - name: CHANGING KERNEL VFS CACHE PRESSURE TO 50
    sysctl:
       name: vm.vfs_cache_pressure
       value: 50

...
