---

- name: SETTING KERNEL HARDENING RULES

  hosts: localhost
  user: fmarinho
  become: yes
  gather_facts: false
  connection: ssh
  
  tasks:

  - name: Setting kernel.core_uses_pid value to '1'
    sysctl:
       name: kernel.core_uses_pid
       value: '1'
       sysctl_file: /etc/sysctl.d/10-lynis-kernel.conf
       sysctl_set: yes

  - name: Setting kernel.ctrl-alt-del value to '0'
    sysctl:
       name: kernel.ctrl-alt-del
       value: '0'
       sysctl_file: /etc/sysctl.d/10-lynis-kernel.conf	
       sysctl_set: yes

  - name: Setting kernel.dmesg_restrict to '1'
    sysctl:
       name: kernel.dmesg_restrict
       value: '1'
       sysctl_file: /etc/sysctl.d/10-lynis-kernel.conf
       sysctl_set: yes

  - name: Setting kernel.kptr_restrict value to '2'
    sysctl:
       name: kernel.kptr_restrict
       value: '2'
       sysctl_file: /etc/sysctl.d/10-lynis-kernel.conf
       sysctl_set: yes

  - name: Setting kernel.randomize_va_space value to '2'
    sysctl:
       name: kernel.randomize_va_space
       value: '2'
       sysctl_file: /etc/sysctl.d/10-lynis-kernel.conf
       sysctl_set: yes

  - name: Setting kernel.sysrq value to '0'
    sysctl:
       name: kernel.sysrq
       value: '0'
       sysctl_file: /etc/sysctl.d/10-lynis-kernel.conf
       sysctl_set: yes

  - name: Setting kernel.yama.ptrace_scope value to '1'
    sysctl:
       name: kernel.yama.ptrace_scope
       value: '1'
       sysctl_file: /etc/sysctl.d/10-lynis-kernel.conf
       sysctl_set: yes

...
