---

- name: SETTING NETWORKING HARDENING RULES

  hosts: localhost
  user: fmarinho
  become: yes
  gather_facts: false
  connection: ssh
  
  tasks:

  - name: 01
    sysctl:
       name: net.ipv4.conf.all.accept_redirects  
       value: 0
       sysctl_file: /etc/sysctl.d/10-lynis-networking.conf
       sysctl_set: yes 

  - name: 02
    sysctl:
       name: net.ipv4.conf.all.accept_source_route
       value: 0
       sysctl_file: /etc/sysctl.d/10-lynis-networking.conf
       sysctl_set: yes

  - name: 03
    sysctl:
       name: net.ipv4.conf.all.bootp_relay
       value: 0
       sysctl_file: /etc/sysctl.d/10-lynis-networking.conf
       sysctl_set: yes

  - name: 04
    sysctl:
       name: net.ipv4.conf.all.forwarding
       value: 0
       sysctl_file: /etc/sysctl.d/10-lynis-networking.conf
       sysctl_set: yes

  - name: 05
    sysctl:
       name: net.ipv4.conf.all.log_martians
       value: 1
       sysctl_file: /etc/sysctl.d/10-lynis-networking.conf
       sysctl_set: yes

  - name: 06
    sysctl:
       name: net.ipv4.conf.all.mc_forwarding
       value: 0
       sysctl_file: /etc/sysctl.d/10-lynis-networking.conf
       sysctl_set: yes
 
  - name: 07
    sysctl:
       name: net.ipv4.conf.all.proxy_arp
       value: 0
       sysctl_file: /etc/sysctl.d/10-lynis-networking.conf
       sysctl_set: yes

  - name: 08
    sysctl:
       name: net.ipv4.conf.all.rp_filter
       value: 1
       sysctl_file: /etc/sysctl.d/10-lynis-networking.conf
       sysctl_set: yes

  - name: 09
    sysctl:
       name: net.ipv4.conf.default.rp_filter
       value: 1
       sysctl_file: /etc/sysctl.d/10-lynis-networking.conf
       sysctl_set: yes

  - name: 09
    sysctl:
       name: net.ipv4.conf.all.send_redirects
       value: 0
       sysctl_file: /etc/sysctl.d/10-lynis-networking.conf
       sysctl_set: yes

  - name: 10
    sysctl: 
       name: net.ipv4.conf.default.accept_redirects 
       value: 0
       sysctl_file: /etc/sysctl.d/10-lynis-networking.conf
       sysctl_set: yes

  - name: 11
    sysctl:
       name: net.ipv4.conf.default.accept_source_route
       value: 0
       sysctl_file: /etc/sysctl.d/10-lynis-networking.conf
       sysctl_set: yes

  - name: 12
    sysctl:
       name: net.ipv4.conf.default.log_martians 
       value: 1
       sysctl_file: /etc/sysctl.d/10-lynis-networking.conf
       sysctl_set: yes

  - name: 13
    sysctl:
       name: net.ipv4.icmp_echo_ignore_broadcasts
       value: 1
       sysctl_file: /etc/sysctl.d/10-lynis-networking.conf
       sysctl_set: yes

  - name: 14
    sysctl:
       name: net.ipv4.icmp_ignore_bogus_error_responses
       value: 1
       sysctl_file: /etc/sysctl.d/10-lynis-networking.conf
       sysctl_set: yes

  - name: 15
    sysctl:
       name: net.ipv4.tcp_syncookies
       value: 1
       sysctl_file: /etc/sysctl.d/10-lynis-networking.conf
       sysctl_set: yes

  - name: 16
    sysctl:
       name: net.ipv4.tcp_timestamps
       value: 0
       sysctl_file: /etc/sysctl.d/10-lynis-networking.conf
       sysctl_set: yes

  - name: 18
    sysctl:
       name: net.ipv6.conf.all.accept_redirects
       value: 0
       sysctl_file: /etc/sysctl.d/10-lynis-networking.conf
       sysctl_set: yes

  - name: 19
    sysctl:
       name: net.ipv6.conf.all.accept_source_route
       value: 0
       sysctl_file: /etc/sysctl.d/10-lynis-networking.conf
       sysctl_set: yes
 
  - name: 20
    sysctl:
       name: net.ipv6.conf.default.accept_redirects
       value: 0
       sysctl_file: /etc/sysctl.d/10-lynis-networking.conf
       sysctl_set: yes

  - name: 21
    sysctl:
       name: net.ipv6.conf.default.accept_source_route
       value: 0
       sysctl_file: /etc/sysctl.d/10-lynis-networking.conf
       sysctl_set: yes

...
