- hosts: servers
  user: stark
  become: yes
  connection: ssh
  gather_facts: false
  tasks:
   - name: UPDATE ALL PACKAGES TO THE LATEST VERSION AVAILABLE 
     apt:
       name:  '*'
       state: latest
