---

- name: USER CREATION PLAYBOOK - EXAMPLE 01
  hosts: localhost
  user: fmarinho
  become: yes  
  connection: ssh
  gather_facts: true	

  vars:
       
       newshell: "{{ newshell }}"
       newlogin: "{{ newlogin }}"
       newpassw: "{{ newpassw }}"
       newdescr: "{{ newdescr }}"
  
  tasks:
  
  - name: Criando o grupo para o novo usu치rio...
    command: groupadd "{{ newlogin }}"
    
  
  - name: Criando o novo usu치rio...
    command: useradd -c "{{ newdescr }}" -g "{{ newlogin }}" -m -s "{{ newshell }}" "{{ newlogin }}"

  
  - name: Criando a senha para o novo usu치rio...
    expect:
      command: passwd "{{ newlogin }}"
      responses:
        (?i)password: "{{ newpassw }}"	

  
  - name: Ajustando o valor do maxdays para o novo usu치rio...
    command: passwd -x 99999 -n 0 "{{ newlogin }}"

...
